spring:
  datasource:
    username: root
    password: 2241260269zjw
    url: jdbc:mysql://localhost:3306/mysql_javafx_db1?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true #���ݿ���е������Զ�ת���շ� e.g.dish_base���dishBase
  mapper-locations: classpath:mybatis/mapper/*.xml  #����mapper�ļ�·��
